data_source retail:
  type: bigquery
  connection:
    account_info_json_path: /usr/local/airflow/include/gcp/service_account.json
    auth_scopes:
    - https://www.googleapis.com/auth/bigquery
    - https://www.googleapis.com/auth/cloud-platform
    - https://www.googleapis.com/auth/drive
    project_id: 'de-airflow-420808'
    dataset: retail

soda_cloud:
  host: cloud.us.soda.io
  api_key_id: a6657648-cf94-4160-841d-ee75d96e1de8
  api_key_secret: cqgsFiKZE3bridlMgTAonzZkriVgy240oMHXQBfW-GKNDyKdPPBUtQ